language: java
dist: trusty
jdk:
- openjdk8
before_install:
- "./scripts/installSkript.sh"
deploy:
  provider: releases
  api_key:
    secure: aq2J0vxFvc3b2ZPhKLybLeYAn0/2P0nbm8ca71W73jM4yxV0XYIindwyNDECgIO49SvETIQVnQAaSw+bSExmyvsKV/hdVUUoq3s4USDfUYQW+7LrKULsq/n2y/ypNY3we68INGFpS5wT8bAYYSGaz2xm4g6yMLsxJ5PhVNOiX+z0d/lJiwvWRMbQVVJn8LlywJDC//fX4W7uTrqcLrcnIWXtHwj4yrnyvDmB+6VruMue+Y/YUjkiqehEoLuJbPTMOa8m9fLERtm/ASjeKSlrqmxaFBHMG70JcGxVysiONXNSapXLdxGUusliRoBpMeYpGc3M4G+FhAaXBP1S1GdmuYnCz1t5LrpSyWl/1M3KEnZDSgU+3SXrPfyCWD/mVRean1IAg4RP1TKTOH5KHkBFD/llUhyV3NSzPGKMFzehpn+BTfvVUcixOl9x/sFu35hl/PCwDt60Tte580W/vd4YR7ShZsLsJ0OqRSNNJfCDIMkfAkGjQff3UWgb5z78D6XAN0oU0NFQK8sGklEi+TnBjG8fQpBGVG1HblNfNqDGEBQQDIvun4cA2LUmfzBZLmeAF75vU24TCIRiBC2KRqRiJZ5Y3xXeu5uayHnbmZvhEqtUqLX4AiLNA+H25+VlgGGRHRHat30R1mWDs0xNdglvC+oh5BtAVu/VQgt/jjURHj0=
  file: plugin/target/MCJukebox.jar
  on:
    tags: true
  skip_cleanup: 'true'
